services:
  # ────────────────────────────────
  # Base PostgreSQL
  # ────────────────────────────────
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: immo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # ────────────────────────────────
  # Application Django (service web)
  # ────────────────────────────────
  web:
    build: ./backend           # ← dossier qui contient Dockerfile
    env_file: .env             # variables si tu utilises .env
    environment:
      # Au minimum l’hôte BD si pas de .env
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_SETTINGS_MODULE: immo.settings
    volumes:
      - ./backend:/code        # hot-reload du code en dev
    ports:
      - "8000:8000"            # http://localhost:8000 
    depends_on:
      - db

volumes:
  db_data:
