# Generated by Django 4.2.22 on 2025-06-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='lease_pdf',
            field=models.FileField(blank=True, null=True, upload_to='leases/'),
        ),
    ]
